---
title: "Current research"
output: html_document
---

I am currently reseraching postgradute student mental health and well-being, supervised by [Dr Maria Gardani](http://https://www.gla.ac.uk/schools/psychology/staff/mariagardani/) and [Prof Stephany Biello](https://www.gla.ac.uk/schools/psychology/staff/stephanybiello/). Our project is funded by University of Glasgow Research and Innovation Services. the study looks into postgraduate research student (PGR) mental health and well-being. [Official records](https://www.hesa.ac.uk/data-and-analysis/students/table-15) show that less than 2% of postgraduate students in the UK report a mental health condition to their institution. Nevertheless, scientific studies using smaller samples paint a different picture, implying that many more postgraduates might be suffering in silence. Recent findings indicate that around half of postgraduate students in the  [States](https://www.deepdyve.com/lp/springer-journal/mental-health-and-suicidal-behavior-among-graduate-students-5eH2yfCwem?key=springer) and [Belgium](https://ciencias.ulisboa.pt/sites/default/files/fcul/investigacao/Work%20organization%20and%20mental%20health%20problems%20in%20PhD%20students.pdf) endorse emotional problems and psychological distress, while around a third of graduate heathcare students in [Brasil](http://www.scielo.br/pdf/rbp/v27n3/a07v27n3.pdf) and [Belgium](https://ciencias.ulisboa.pt/sites/default/files/fcul/investigacao/Work%20organization%20and%20mental%20health%20problems%20in%20PhD%20students.pdf) show symptoms of common mental disorders, including stress, insomnia, fatigue, irritability, forgetfulness, anhedonia, inability to concentrate or overcome difficulties. According to the a large survey at [Berkeley, California](http://ga.berkeley.edu/wp-content/uploads/2015/04/wellbeingreport_2014.pdf), main predictors of graduate mental health and life satisfaction include career prospects, overall health, living conditions, academic engagement, and social support.

<br>
Postgraduate research students (PGR’s) might be particularly vulnerable to mental ill-health, as years of independent study within a challenging unstructured programme can make for a very stressful, solitary experience. A [recent report on PGR’s mental health and wellbeing](https://re.ukri.org/documents/2018/mental-health-report/
) indicates that many PGR’s in the UK, especially the part time, mature, interdisciplinary or international students, or those doing field work, report loneliness and isolation. In addition, [PGR’s who report a mental health condition](https://www.heacademy.ac.uk/knowledge-hub/postgraduate-research-experience-survey-report-2017) also report lower satisfaction with life and with life-work balance and are much more likely to consider suspending or abandoning their studies than their counterparts who don't report mental ill-health. 

<br>
Nevertheless, our knowledge of mental health problems in PGR’s in the UK is still scarce and largely based on official university records rather than scientific research. In our current study, we aim to create new knowledge on mental health and well-being of Scottish PGR's by using survey data and focus groups to analyse the prevalence and provenance of PGR mental health problems. We are also looking into the role of the supervisory relationship in PGR well-being, as well as the support supervisors need to perform their pastoral role as best as they can. In addition, we are working on a systematic review of prevalence of mental health problems in postgraduates. The review pre-registration is currently awaiting approval at [PROPERO - The International Prospective Register of Systematic Reviews](https://www.crd.york.ac.uk/prospero/).




