---
title: "  "
output: html_document
---
<br>

# **Education**
* MSc Research Methods of Psychological Science 
University of Glasgow
<br>
Expected completion: September, 2019. 
<br>
Thesis topic: "PGR Student Mental Health and Well-Being" 
Supervised by [Dr Maria Gardani](https://www.gla.ac.uk/schools/psychology/staff/mariagardani/) and [Prof Stephany Biello](https://www.gla.ac.uk/schools/psychology/staff/stephanybiello/). 

* MA Hons Psychology 
University of Glasgow, 2018.
<br>
Thesis title: “Personal relationships in Trichotillomania”
<br>
Supervised by [Dr Maxine Swingler](https://www.gla.ac.uk/schools/psychology/staff/maxineswingler/) and [Judith Stevenson](https://www.gla.ac.uk/schools/psychology/staff/judestevenson/)

* PGC TESOL
Sheffield Hallam University, 2013.
<br>
Thesis title: "Error Correction in ESOL Classroom"

* MA English Studies 
University of Sheffield, 2011.
<br>
Thesis title: “You and Thou in Shakespeare’s plays”
<br>
Supervised by [Prof Emeritus James Fitzmaurice](https://www.sheffield.ac.uk/english/people/fitzmauricej)

* BA in Slavonic studies 
University of Belgrade, 2011.
<br><br>

# **Professional Training & Skills**
* Using R Studio for data wrangling, analysis, visualisation and simulation

* RMarkdown repoducible scripts and web design

* Data recording and analysis using SPSS

* Qualitative Software NVivo

* Designing and conducting qualitative interviews and focus groups

* Systematic review and meta-analysis software: EPPI-4, Rayyan, Distiller, RevMan 5

* Participant preparation and safety measures in MEG studies

* Peer and self-observation in educational research

* CLIL: Content and Language Integradted Learning 

* Jolly Phonics: A Phonetic Approach to Teaching Literacy

* Cambridge ESOL Oral Langauge Assessment: examiner training for all levels of 
profieciency

* Using Emotional Intelligence in Teaching

* Teaching Foreign Language through Arts and Crafts


