---
title: "Employment"
output: html_document
---


* 2015-2016 	Lecturer of Academic English; University of the West of Scotland, Paisley

* 2012-2014 	Lecturer of English as a Foreign Language; European University of Madrid, Spain

* 2011-2014	Cambridge ESOL Speaking Examiner, Escuelas Catolicas, Madrid, Spain

* 2008 -2012 	English Teacher, Primary School Mirabal, Madrid; Big Ben School, Burgos, Spain

* 2004-2008	English Teacher; Big Ben Language School, Burgos, Spain

* 2000-2003 	Freelance Translator; London

* 1997-2003 	Journalist, UK correspondent; Weekly Newspaper “Pancevac”, Radio Pancevo, Serbia
<br><br>

## Teaching experience

* University of Glasgow
Mentoring an undergraduate student, advising on qualitative methodology for her final project on Trichotillomania and expressed emotion 

* University of the West of Scotland, UK
Listening, speaking and presentation skills for Academic English for international undergraduate and graduate students

* European University of Madrid, Spain
    General English courses for undergraduate students
    English for Academic Purposes
    General English course for academic staff  
    Teacher training workshops on error correction
    Teacher training in Common European Framework of Reference       for Languages
    Teacher Training in Language Testing

* Primary School Mirabal, Madrid, Spain
English as a second language classes for primary school
Phonics and literacy classes
Arts and crafts classes

* Big Ben Language School
English as a foreign language classes for children and adults
Cambridge Exam preparation classes 

