---
title: "Jelena Milicev - Academic Page"
---

I am a postgraduate student in the University of Glasgow's
[Institute of Neuroscience and Psychology](http://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/).
I work with [Dr Maria Gardani](http://https://www.gla.ac.uk/schools/psychology/staff/mariagardani/)

\newline

### Contact details
* Work email: 2148601m@student.gla.ac.uk
* Personal email: pancevo@msn.com
* Phone: +44 7899397038

# EDUCATION

MSc Research Methods of Psychological Science (University of Glasgow, expected completion September, 2019)
MA Hons Psychology (University of Glasgow, 2018) Thesis title: “Personal relationships in Trichotillomania”, supervised by Dr Maxine Swingler and Judith Stevenson
PGC TESOL (Sheffield Hallam University, 2013)
MA English Studies (University of Sheffield, 2011) Thesis title: “You and Thou in Shakespeare’s plays”, supervised by Dr James Fitzmaurice 
BA in Slavonic studies (University of Belgrade, 2011)


# EMPLOYMENT

2015-2016 	Lecturer of Academic English; University of the West of Scotland, Paisley
2012-2014 	Lecturer of English as a Foreign Language; European University of Madrid, Spain
2011-2014	Cambridge ESOL Speaking Examiner, Escuelas Catolicas, Madrid, Spain
2008 -2012 	English Teacher, Primary School Mirabal, Madrid; Big Ben School, Burgos, Spain
2004-2008	English Teacher; Big Ben Language School, Burgos, Spain
2000-2003 	Freelance Translator; London
1997-2003 	Journalist, UK correspondent; Weekly Newspaper “Pancevac”, Radio Pancevo, Serbia

# PUBLICATIONS 

2019	Kocic, A. & Milicev, J. (2019) Where is Local in a National Region? International Journal of Digital Media and Policy (in press)
2014 	Milicev, J. (2014) Correct Me if I’m Wrong, but Do It Right: Error Correction and Learner Uptake in University-level EFL Classrooms. Athens Journal of Philology, 1, 4, 259-71



