---
title: "  "
output: 
  html_document:
    toc: FALSE
---
<br>

# **My Abstracts**
<br>

* **"Trichotillomania and Personal Relationships"**
<br>
(Milicev, J, Stevenson J., Swingler, M., in preparation)
<br>
_Quantitative research links Trichotillomania (hair pulling disorder) with severe psychosocial impairments and reduced quality of personal relationships, but little is known about the lived experiences of personal relationships in Trichotillomania.
The current study uses Interpretative phenomenological analysis to explore experiences and perceptions of personal relationships of 6 self-reported female hair pullers in Scotland. Semi-structured in-depth interviews were conducted to collect the data. Three master themes were pertinent to all participants: All in the family; Hair pulling and intimate relationships; and Hair pullers’ interpersonal style. It was found that experiences of family crisis and isolation preceded the onset, while negative family responses to pulling had adverse effects on the condition, the puller’s wellbeing and family relationships. Nevertheless, participants used empathy and forgiveness to repair family ties. Contrary to previous findings, intimate relationships were linked with positive outcomes, while interpersonal style was somewhat ambivalent, characterised by prosocial initiatives as well as social avoidance. The findings further the field by highlighting the positive ways in which personal relationships and hair pulling interact, which has implications for the understanding and treatment of the condition._
<br><br>

* **"Where is Local in a National Region?"**
<br>
(Kocic, A. & Milicev, J., in press, 2019)
<br>
_Scotland does not have any public service radio on a local level, except for a few bulletins or programmes offered by BBC Radio Scotland on an opt-out basis. Scottish commercial radio stations do cover local issues, but within brief hourly news bulletins, without any in-depth coverage, while community radio by and large lacks resources for any news coverage of its own. The present study employs interviews with stakeholders and experts, as well as citizen focus groups, to explore the preceptions of the role of local radio in Scotland, formulating several possible solutions for future local news provision in this region._
<br><br>

* [**"Correct Me if I'm Wrong But Do It Right"**](https://www.researchgate.net/publication/283644363_ATINER's_Conference_Paper_Series_LNG2014-1238_Error_Correction_and_Learner_Uptake_in_University-level_EFL_Classrooms)
<br>
(Milicev, J., 2014)
<br>
_This paper presents the findings on corrective feedback and learner uptake in six university-level EFL classrooms. The study was undertaken by means of observation of ten hours of classroom interaction, five at A1 and another five at B2 level. The classroom observation instrument, developed for the purpose of this research, comprised seven categories for error correction and six for learner uptake. The instrument was used to record the frequency of different types of error correction and learner uptake, as well as the patterns in their co- occurrence. The results show that explicit correction is the predominant type of corrective feedback, to which students normally respond with repetition of the correct form. This tendency is particularly salient in A1 classes, whereas B2 teachers tend to favour recasts, although they do not typically generate learner uptake. Other error correction methods like prompts, explanations, questions, disapproval and error repetition were used less frequently, in spite of the fact that they were highly effective at generating learner uptake and student self- repair._
<br><br>

* [**"Words of Passion, Words of Rage - You and Thou in Shakespeare's Othello"**](https://www.researchgate.net/publication/283644307_You_and_Thou_in_Shakespeare's_Othello)
<br>
(Milicev, J., 2014)
<br>
_As a Venetian general, Othello is addressed with a respectful 'you'. He, in turn, addresses Desdemona with an affectionate 'thou', and Cassio with a respectful 'you'. As the plot unfolds, the original pronominal choices shift. This paper focuses on such shifts as subtle but unfailing clues for the interpretation of the changing dynamics between the characters leading up to the tragic outcome._