---
title: "  "
output: 
  html_document:
    toc: FALSE

---
<br>

## **Reserch experience**
* **2018:**	Systematic review and meta-analysis of the prevalence of mental health problems in the graduate population
Received funding from Research and Innovation Services, University of Glasgow. Devised search strategy and used Distiller systematic review software to search literature and perform meta-analysis.

* **2018:**	Academic paper “Where is Local in a National Region?” 
Advised on qualitative methodology for the study, performed and wrote up qualitative thematic analysis of the focus group data. Co-wrote the Methods section.   

* **2018:**	Final undergraduate student project “Personal relationships in Trichotillomania”
Used semi-structured interviewing and Interpretative Phenomenological Analysis to collect and analyse qualitative data. 

* **2017:**	Summer Trainee Internship, funded by Erasmus Plus Scheme,
at the Department of Clinical Psychology and the University Counselling Clinic, Complutense University, Madrid. Assisted in ongoing studies on self-serving bias in paranoia; recorded participant clinical data in SPSS, assisted in clinical interviews and participant assessment, assisted in participant preparation for MEG studies. Attended clinical meetings at the Complutense Psychological Clinic, seminars and workshops on network analysis using R and systematic reviews and meta-analysis using RevMan 5. Recorded clinical data for a network analysis of depression and anxiety symptoms. 

* **2016:**	Student-led research study into Facial Perception and Trustworthiness at the Science Centre, Glasgow
Engaged with the public, recruited participants, collected participant data, conducted economic game experiment with children and adults.

* **2013:**	Error correction in university-level English as a foreign language classroom at the European University of Madrid, Spain.
Undertook classroom observation to record a variety of error correction techniques; recorded rates of successful learner uptake for each technique.